/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "jdacayyuuelutqxxqoww"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkYWNheXl1dWVsdXRxeHhxb3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwODExMTUsImV4cCI6MjA4NjY1NzExNX0.S8iQn1l-Km8nSBHqP2T0VqZXnMk9KF_bZiTW_-FikHk"